name: gestion_de_flotas
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:    ^1.0.8
  go_router:          ^14.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.9.0
  build_runner:       ^2.4.14
  flutter_lints:      ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/Maven_Pro/MavenPro-Black.ttf
        - asset: assets/fonts/Maven_Pro/MavenPro-Bold.ttf
        - asset: assets/fonts/Maven_Pro/MavenPro-ExtraBold.ttf
        - asset: assets/fonts/Maven_Pro/MavenPro-Medium.ttf
        - asset: assets/fonts/Maven_Pro/MavenPro-Regular.ttf
        - asset: assets/fonts/Maven_Pro/MavenPro-SemiBold.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: false
    rive: false
    lottie: false
